services:
  - type: worker
    name: nick-bomber-bot
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        value: 7860365469
